puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Abraham Thomas"
puts "Andrey Krahmal"
puts "Ayaz Goulamabasse"
puts "Berta Gutierrez"
puts "Biwek Shrestha"
puts "Colin Frankish"
puts "James Hunter"
puts "Jorja Hung"
puts "Kalle Malmiharju"
puts "Liviu Cojocar"
puts "Makis Otman"
puts "Megan Folsom"
puts "Nabin"
puts "Peter Saxton"
puts "Rolando Barbella"
puts "Roy"